/* GENERATED by tools/build_swiftee_assets.py — do not edit by hand. */
window.NL.SwifteeData =
{
 "cell": 256,
 "clips": {
  "blinking": {
   "cols": 7,
   "frames": 40,
   "ink": [
    0.1523,
    0.1055,
    0.8633,
    0.8867
   ],
   "rows": 6
  },
  "celebrate_start": {
   "cols": 3,
   "frames": 8,
   "ink": [
    0.0898,
    0.1055,
    0.9102,
    0.8867
   ],
   "rows": 3
  },
  "celebrating": {
   "cols": 8,
   "frames": 50,
   "ink": [
    0.0156,
    0.0195,
    1.0,
    0.8906
   ],
   "rows": 7
  },
  "confident": {
   "cols": 7,
   "frames": 45,
   "ink": [
    0.1484,
    0.0781,
    0.8438,
    0.875
   ],
   "rows": 7
  },
  "confused": {
   "cols": 7,
   "frames": 40,
   "ink": [
    0.1602,
    0.1523,
    0.8164,
    0.875
   ],
   "rows": 6
  },
  "confused_start": {
   "cols": 3,
   "frames": 7,
   "ink": [
    0.1523,
    0.1055,
    0.8633,
    0.8867
   ],
   "rows": 3
  },
  "curious": {
   "cols": 6,
   "frames": 33,
   "ink": [
    0.0781,
    0.0859,
    0.875,
    0.8828
   ],
   "rows": 6
  },
  "excited": {
   "cols": 9,
   "frames": 72,
   "ink": [
    0.1445,
    0.0625,
    0.8984,
    0.8867
   ],
   "rows": 8
  },
  "flapping": {
   "cols": 6,
   "frames": 27,
   "ink": [
    0.1367,
    0.1055,
    0.8633,
    0.8867
   ],
   "rows": 5
  },
  "focussed": {
   "cols": 7,
   "frames": 37,
   "ink": [
    0.1719,
    0.1016,
    0.7969,
    0.8828
   ],
   "rows": 6
  },
  "happy": {
   "cols": 7,
   "frames": 40,
   "ink": [
    0.125,
    0.1055,
    0.8711,
    0.8867
   ],
   "rows": 6
  },
  "happy_start": {
   "cols": 3,
   "frames": 7,
   "ink": [
    0.1523,
    0.1055,
    0.8633,
    0.8867
   ],
   "rows": 3
  },
  "listening": {
   "cols": 7,
   "frames": 40,
   "ink": [
    0.1406,
    0.0938,
    0.8281,
    0.9141
   ],
   "rows": 6
  },
  "playful": {
   "cols": 6,
   "frames": 30,
   "ink": [
    0.1602,
    0.0977,
    0.9102,
    0.875
   ],
   "rows": 5
  },
  "playful_start": {
   "cols": 4,
   "frames": 10,
   "ink": [
    0.1523,
    0.1016,
    0.8945,
    0.8867
   ],
   "rows": 3
  },
  "proud": {
   "cols": 7,
   "frames": 40,
   "ink": [
    0.1445,
    0.082,
    0.8242,
    0.875
   ],
   "rows": 6
  },
  "proud_start": {
   "cols": 3,
   "frames": 7,
   "ink": [
    0.0977,
    0.1016,
    0.875,
    0.8867
   ],
   "rows": 3
  },
  "surprised": {
   "cols": 7,
   "frames": 47,
   "ink": [
    0.1523,
    0.1016,
    0.8633,
    0.8867
   ],
   "rows": 7
  },
  "surprised_start": {
   "cols": 3,
   "frames": 8,
   "ink": [
    0.1523,
    0.1055,
    0.8633,
    0.8867
   ],
   "rows": 3
  },
  "talk_start": {
   "cols": 2,
   "frames": 3,
   "ink": [
    0.1523,
    0.1055,
    0.8633,
    0.8867
   ],
   "rows": 2
  },
  "talking": {
   "cols": 3,
   "frames": 8,
   "ink": [
    0.1523,
    0.1055,
    0.8633,
    0.8867
   ],
   "rows": 3
  },
  "thinking": {
   "cols": 7,
   "frames": 47,
   "ink": [
    0.1719,
    0.1016,
    0.8203,
    0.8867
   ],
   "rows": 7
  },
  "wave_start": {
   "cols": 3,
   "frames": 7,
   "ink": [
    0.0898,
    0.1055,
    0.9102,
    0.8867
   ],
   "rows": 3
  },
  "waving": {
   "cols": 6,
   "frames": 30,
   "ink": [
    0.0586,
    0.1055,
    0.8945,
    0.8867
   ],
   "rows": 5
  }
 },
 "dir": "assets/swiftee/",
 "foot": 0.8867,
 "fps": 20,
 "poster": {
  "cell": 128,
  "cols": 4,
  "file": "poster.webp",
  "index": {
   "blinking": 0,
   "celebrating": 1,
   "confident": 2,
   "confused": 3,
   "curious": 4,
   "excited": 5,
   "flapping": 6,
   "focussed": 7,
   "happy": 8,
   "listening": 9,
   "playful": 10,
   "proud": 11,
   "surprised": 12,
   "talking": 13,
   "thinking": 14,
   "waving": 15
  },
  "rows": 4
 },
 "stand": 0.7812
};
