/* GENERATED by tools/build_swiftee_assets.py — do not edit by hand. */
window.NL.SwifteeData =
{
 "cell": 256,
 "clips": {
  "blinking": {
   "cols": 7,
   "frames": 40,
   "rows": 6
  },
  "celebrate_start": {
   "cols": 3,
   "frames": 8,
   "rows": 3
  },
  "celebrating": {
   "cols": 8,
   "frames": 50,
   "rows": 7
  },
  "confident": {
   "cols": 7,
   "frames": 45,
   "rows": 7
  },
  "confused": {
   "cols": 7,
   "frames": 40,
   "rows": 6
  },
  "confused_start": {
   "cols": 3,
   "frames": 7,
   "rows": 3
  },
  "curious": {
   "cols": 6,
   "frames": 33,
   "rows": 6
  },
  "excited": {
   "cols": 9,
   "frames": 72,
   "rows": 8
  },
  "flapping": {
   "cols": 6,
   "frames": 27,
   "rows": 5
  },
  "focussed": {
   "cols": 7,
   "frames": 37,
   "rows": 6
  },
  "happy": {
   "cols": 7,
   "frames": 40,
   "rows": 6
  },
  "happy_start": {
   "cols": 3,
   "frames": 7,
   "rows": 3
  },
  "listening": {
   "cols": 7,
   "frames": 40,
   "rows": 6
  },
  "playful": {
   "cols": 6,
   "frames": 30,
   "rows": 5
  },
  "playful_start": {
   "cols": 4,
   "frames": 10,
   "rows": 3
  },
  "proud": {
   "cols": 7,
   "frames": 40,
   "rows": 6
  },
  "proud_start": {
   "cols": 3,
   "frames": 7,
   "rows": 3
  },
  "surprised": {
   "cols": 7,
   "frames": 47,
   "rows": 7
  },
  "surprised_start": {
   "cols": 3,
   "frames": 8,
   "rows": 3
  },
  "talk_start": {
   "cols": 2,
   "frames": 3,
   "rows": 2
  },
  "talking": {
   "cols": 3,
   "frames": 8,
   "rows": 3
  },
  "thinking": {
   "cols": 7,
   "frames": 47,
   "rows": 7
  },
  "wave_start": {
   "cols": 3,
   "frames": 7,
   "rows": 3
  },
  "waving": {
   "cols": 6,
   "frames": 30,
   "rows": 5
  }
 },
 "dir": "assets/swiftee/",
 "foot": 0.8867,
 "fps": 20,
 "poster": {
  "cell": 128,
  "cols": 4,
  "file": "poster.webp",
  "index": {
   "blinking": 0,
   "celebrating": 1,
   "confident": 2,
   "confused": 3,
   "curious": 4,
   "excited": 5,
   "flapping": 6,
   "focussed": 7,
   "happy": 8,
   "listening": 9,
   "playful": 10,
   "proud": 11,
   "surprised": 12,
   "talking": 13,
   "thinking": 14,
   "waving": 15
  },
  "rows": 4
 },
 "stand": 0.7812
};
